name: Review action
on: pull_request
jobs:
    review:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: setup java
              uses: actions/setup-java@v3
              with:
                    distribution: "temurin"
                    java-version: "17"
            - run: java --version